import math

WIDTH=1600
HEIGHT=900
HALF_WIDTH = WIDTH//2
HALF_HEIGHT = HEIGHT//2
FPS=60
MAP_WIDTH = 16
MAP_HEIGHT = 9
TILE_SIZE = min(WIDTH // MAP_WIDTH, HEIGHT // MAP_HEIGHT)
PLAYER_POS=(1.5,5)
PLAYER_ANGLE=0
PLAYER_SPEED=0.004
PLAYER_ROT=0.001

FOV = math.pi/3
HALF_FOV = FOV/2
NUM_RAYS = 800
HALF_NUM_RAYS = 400
DELTA_ANGLE = FOV/NUM_RAYS
MAX_DEPTH=20

SCREEN_DIST = HALF_WIDTH/math.tan(HALF_FOV)
SCALE = WIDTH//NUM_RAYS